apiVersion: v1
kind: Service
metadata:
  name: compressor-svc
  namespace: compressor
  labels:
    app: compressor
spec:
  type: NodePort
  selector:
    app: compressor
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30080
    - name: grpc
      port: 5002
      targetPort: 5002
      nodePort: 30082
