{
 "title": "Compressor tests",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "handlers",
    "query": {
     "query": "label_values({network_protocol_version=\"2\"},http_route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "gRPC RPS by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method) (rate(grpc_requests_received_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed images rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(image_processing_image_counter[$__rate_interval])",
     "legendFormat": "images"
    }
   ]
  },
  {
   "title": "Cache rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(image_processing_cache_hits_total[$__rate_interval]))",
     "legendFormat": "hit"
    },
    {
     "expr": "sum(rate(image_processing_cache_misses_total[$__rate_interval]))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Hit ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(image_processing_cache_hits_total) / (sum(image_processing_cache_hits_total) + sum(image_processing_cache_misses_total)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Latency by $handlers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "repeat": "handlers",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{http_route=~\"$handlers\"}[$__rate_interval])) by (le))",
     "legendFormat": "q99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{http_route=~\"$handlers\"}[$__rate_interval])) by (le))",
     "legendFormat": "q90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{http_route=~\"$handlers\"}[$__rate_interval])) by (le))",
     "legendFormat": "q50"
    }
   ]
  }
 ]
}