name: Publish Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [win-x64, linux-x64, osx-x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          dotnet-quality: 'preview'

      - name: Restore dependencies
        run: dotnet restore src/CompressorService.Api/CompressorService.Api.csproj

      - name: Build project
        run: dotnet build src/CompressorService.Api/CompressorService.Api.csproj --configuration Release --no-restore

      - name: Publish for ${{ matrix.rid }}
        run: |
          dotnet publish src/CompressorService.Api/CompressorService.Api.csproj \
            --configuration Release \
            --runtime ${{ matrix.rid }} \
            --self-contained true \
            --output ./publish/${{ matrix.rid }} \
            /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true

      - name: Archive binaries for ${{ matrix.rid }}
        run: |
          cd publish
          zip -r CompressorService-${{ matrix.rid }}.zip ${{ matrix.rid }}
          mv CompressorService-${{ matrix.rid }}.zip ../

      - name: Publish Release Asset
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Автоматически сгенерированный релиз для тега **${{ github.ref_name }}**.
          files: CompressorService-${{ matrix.rid }}.zip
